//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enerji_Takip
    {
        public int id { get; set; }
        public int fatura_turu { get; set; }
        public System.DateTime fatura_tarihi { get; set; }
        public string fatura_no { get; set; }
        public double fatura_tutari { get; set; }
        public string aciklama { get; set; }
        public int kaydeden_kullanici { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
        public int aktif { get; set; }
        public string abone_no { get; set; }
        public Nullable<int> yil { get; set; }
        public Nullable<int> donem { get; set; }
        public Nullable<int> butce_turu { get; set; }
        public string musteri_tarife_grup { get; set; }
        public Nullable<int> ihale_durumu { get; set; }
        public Nullable<int> tek_cok_zamanli { get; set; }
        public Nullable<System.DateTime> ilk_okuma_tarihi { get; set; }
        public Nullable<System.DateTime> son_okuma_tarihi { get; set; }
        public Nullable<int> ortalama_kwh { get; set; }
        public Nullable<int> gun_ilk_endeks { get; set; }
        public Nullable<int> puantaj_ilk_endeks { get; set; }
        public Nullable<int> gece_ilk_endeks { get; set; }
        public Nullable<int> gun_son_endeks { get; set; }
        public Nullable<int> puantaj_son_endeks { get; set; }
        public Nullable<int> gece_son_endeks { get; set; }
        public Nullable<int> gun_fark { get; set; }
        public Nullable<int> puantaj_fark { get; set; }
        public Nullable<int> gece_fark { get; set; }
        public Nullable<int> gun_carpan { get; set; }
        public Nullable<int> puantaj_carpan { get; set; }
        public Nullable<int> gece_carpan { get; set; }
        public Nullable<int> gun_tuketim { get; set; }
        public Nullable<int> puantaj_tuketim { get; set; }
        public Nullable<int> gece_tuketim { get; set; }
        public Nullable<int> toplam_tuketim { get; set; }
        public Nullable<int> gun_birim_fiyati { get; set; }
        public Nullable<int> puantaj_birim_fiyati { get; set; }
        public Nullable<int> gece_birim_fiyati { get; set; }
        public Nullable<int> gun_toplam { get; set; }
        public Nullable<int> puantaj_toplam { get; set; }
        public Nullable<int> gece_toplam { get; set; }
        public Nullable<int> toplam_tutar { get; set; }
        public Nullable<int> trafo_kaybi_bedeli { get; set; }
        public Nullable<int> dagitim_bedeli { get; set; }
        public Nullable<int> ceza_bedeli { get; set; }
        public Nullable<int> iletisim_bedeli { get; set; }
        public Nullable<int> per_ok_bedeli { get; set; }
        public Nullable<int> per_sat_hiz_bedeli { get; set; }
        public Nullable<int> kk_bedeli { get; set; }
        public Nullable<int> toplam { get; set; }
        public Nullable<int> enerji_fonu { get; set; }
        public Nullable<int> trt_payi { get; set; }
        public Nullable<int> tuketim_vergisi { get; set; }
        public Nullable<int> gecikme_zammi { get; set; }
        public Nullable<int> kdv_matrahi { get; set; }
        public Nullable<int> kdv { get; set; }
        public Nullable<int> fiyat_farki { get; set; }
        public Nullable<int> yakit_turu { get; set; }
        public Nullable<int> kati_yakit_turu { get; set; }
        public Nullable<int> dogal_gaz_durumu { get; set; }
        public Nullable<int> alim_miktari { get; set; }
        public Nullable<int> birim_fiyati { get; set; }
        public Nullable<int> su_turu { get; set; }
        public string abone_tipi { get; set; }
        public Nullable<int> tuketim_kredi { get; set; }
        public Nullable<int> ctv { get; set; }
        public Nullable<int> atik_su_bedeli { get; set; }
        public Nullable<int> atik_su_kdv { get; set; }
        public Nullable<int> su_bedeli { get; set; }
        public Nullable<int> bakim_ucreti { get; set; }
        public Nullable<int> diger_odemeler { get; set; }
        public Nullable<int> sayac_turu { get; set; }
        public string turu { get; set; }
        public Nullable<int> kullanilan_mb { get; set; }
        public Nullable<int> atik_miktari { get; set; }
        public string dekont_no { get; set; }
        public Nullable<int> serbest_tuketici { get; set; }
        public Nullable<int> kompanzasyon { get; set; }
        public Nullable<int> bina_id { get; set; }
    
        public virtual Binalar Binalar { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
